spring:
  application:
    name: vehicle-service
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8082